name: All in one build

on:
  # pull_request:
  push:
    branches:
      - ci/improve-make
      - merge-eventstore-pipeline

permissions:
  contents: write
  packages: write

jobs:

  # core:
  #   uses: ./.github/workflows/core.yml
  #   with:
  #     node_version: '18'
  #     buf_version: 'latest'
  #     go_version: '1.20'
    
  # console:
  #   uses: ./.github/workflows/console.yml
  #   with:
  #     node_version: '18'
  #     buf_version: 'latest'

  # version:
  #   uses: ./.github/workflows/version.yml
  #   with:
  #     semantic_version: '19.0.2'
  #     dry_run: true

  # compile:
  #   needs: [core, console, version]
  #   uses: ./.github/workflows/compile.yml
  #   with:
  #     go_version: '1.20'
  #     core_cache_key: ${{ needs.core.outputs.cache_key }}
  #     console_cache_key: ${{ needs.console.outputs.cache_key }}
  #     core_cache_path: ${{ needs.core.outputs.cache_path }}
  #     console_cache_path: ${{ needs.console.outputs.cache_path }}
  #     version: ${{ needs.version.outputs.version }}

  # core-unit-test:
  #   needs: core
  #   uses: ./.github/workflows/core-unit-test.yml
  #   with:
  #     go_version: '1.20'
  #     core_cache_key: ${{ needs.core.outputs.cache_key }}
  #     core_cache_path: ${{ needs.core.outputs.cache_path }}
      
  # core-integration-test:
  #   needs: core
  #   uses: ./.github/workflows/core-integration-test.yml
  #   with:
  #     go_version: '1.20'
  #     core_cache_key: ${{ needs.core.outputs.cache_key }}
  #     core_cache_path: ${{ needs.core.outputs.cache_path }}
  
  # lint:
  #   needs: [core, console]
  #   uses: ./.github/workflows/lint.yml
  #   with:
  #     go_version: '1.20'
  #     node_version: '18'
  #     buf_version: 'latest'
  #     go_lint_version: 'v1.53.2'
  #     core_cache_key: ${{ needs.core.outputs.cache_key }}
  #     core_cache_path: ${{ needs.core.outputs.cache_path }}
  #     core_cache_hit: ${{ needs.core.outputs.cache_hit }}
  #     console_cache_hit: ${{ needs.console.outputs.cache_hit }}

  # container:
  #   needs: [compile]
  #   uses: ./.github/workflows/container.yml
  #   with:
  #     tag_name: ghcr.io/zitadel/test:${{ github.sha }}

  # e2e:
  #   uses: ./.github/workflows/e2e.yml
  #   needs: [container]
  #   with:
  #     tag_name: ${{ needs.container.outputs.tag_name }}-ubuntu
  
  e2e:
    uses: ./.github/workflows/e2e.yml
    with:
      tag_name: ghcr.io/zitadel/test:136fba1bdd5c74bfe2deeb0ef6619ba6b957d5a4-ubuntu

  # release:
  #   uses: ./.github/workflows/release.yml
  #   # needs: [version, core-unit-test, core-integration-test, lint, container, e2e]
  #   needs: [version, core-unit-test, core-integration-test, container, e2e]
  #   if: ${{ needs.version.outputs.published == 'true' }}
  #   with:
  #     node_version: '16'
  #     buf_version: 'latest'
  #     # tag_name: ghcr.io/zitadel/test:d2021f68a732839d18f2ff9ca78fc018dbe91320
  #     tag_name: ${{ needs.container.outputs.tag_name }}
  #     semantic_version: '19.0.2'
  #     image_name: 'ghcr.io/zitadel/test'
