name: Container

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
    outputs:
      tag_name:
        value: ${{ inputs.tag_name }}

jobs:

  zitadel:
    name: zitadel
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: 'image=moby/buildkit:v0.11.6'
      - 
        name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        uses: actions/download-artifact@v3
      - 
        name: ubuntu
        uses: docker/build-push-action@v4
        timeout-minutes: 4
        with:
          context: .
          file: build/Dockerfile
          target: artifact
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ inputs.tag_name }}-ubuntu
      - 
        name: scratch
        uses: docker/build-push-action@v4
        timeout-minutes: 4
        with:
          context: .
          file: build/Dockerfile
          target: final
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ inputs.tag_name }}