name: Release

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      buf_version:
        required: true
        type: string
      semantic_version:
        required: true
        type: string
      tag_name:
        required: true
        type: string
      image_name:
        required: true
        type: string

jobs:
  version:
    uses: ./.github/workflows/version.yml
    with:
      semantic_version: '19.0.2'
      dry_run: true

  docker:
    runs-on: ubuntu-22.04
    needs: [ version ]
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Publish ${{ needs.version.outputs.version }}
      run: |
        docker buildx imagetools create \
          --tag ${{ inputs.image_name }}:${{ needs.version.outputs.version }} \
          ${{ inputs.tag_name }}
        docker buildx imagetools create \
          --tag ${{ inputs.image_name }}:${{ needs.version.outputs.version }}-ubuntu \
          ${{ inputs.tag_name }}-ubuntu
    -
      name: Publish latest
      if: ${{ github.ref_name == 'main' }}
      run: |
        docker buildx imagetools create \
          --tag ${{ inputs.image_name }}:latest \
          ${{ inputs.tag_name }}
        docker buildx imagetools create \
          --tag ${{ inputs.image_name }}:latest-ubuntu \
          ${{ inputs.tag_name }}-ubuntu





    
  # api:
  #   name: api
  #   runs-on: ubuntu-latest
  #   needs: [release]
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: bufbuild/buf-setup-action@v1
  #     with:
  #       version: ${{ inputs.buf_version }}
  #       github_token: ${{ github.token }}
  #   - uses: bufbuild/buf-push-action@v1
  #     with:
  #       buf_token: ${{ secrets.buf_token }}
  #       # input: proto
  #       ## Currently no tags are supported in the action https://github.com/bufbuild/buf-push-action/issues/20
  #       draft: ${{ github.ref_name != 'main'}}

  #console:

  #core:
