name: Version

on:
  workflow_call:
    inputs:
      semantic_version:
        required: true
        type: string
      dry_run:
        required: true
        type: boolean
    outputs:
        version: 
            value: ${{ jobs.generate.outputs.version }}
        published: 
            value: ${{jobs.generate.outputs.published }}

jobs:
  generate:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      version: v${{ steps.semantic.outputs.new_release_version }}
      published: ${{ steps.semantic.outputs.new_release_published }}
    steps:
    - name: Source checkout
      uses: actions/checkout@v3
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        dry_run: ${{ inputs.dry_run }}
        semantic_version: ${{ inputs.semantic_version }}
        extra_plugins: |
          @semantic-release/exec@6.0.3
